services:
  public-app:
    image: 039612870052.dkr.ecr.ca-central-1.amazonaws.com/public-app:latest
    ports:
      - "8000:8000"
    volumes:
      - app-data:/data
    restart: unless-stopped
    networks:
      - cloudnet

volumes:
  app-data:

networks:
  cloudnet:
    external: true
