services:
  public-app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - app-data:/data
    restart: unless-stopped
    networks:
     - cloudnet

volumes:
  app-data:


networks:
  cloudnet:
    external: true
